/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package info.akang.covid

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = DataETL()
    }
}
